### ISSUE TITLE
Oculus Quest Support

### ISSUE THREAD

**Issue by kabrio** [stalgiag/p5.xr#105]
#### New feature details:

Hello, 

creative coder practitioner and teacher here. 
Super excited to have this, thank you!
Do you think it is realistic, that this will work on Oculus Quest anytime soon?

Best
K

**Comment by kabrio** [comment]
I can get this running on my quest but the image is only displayed on the right screen of my Quest 1.
https://editor.p5js.org/deleted_user/present/HF_TcM4ZP

**Comment by Vargol** [comment]
Hi, not the author of this code but I have used it and its works fine with my Quest 1.

For example.....

https://editor.p5js.org/Vargol/full/bC3nSABEI

Also the VR examples for the p5xr.org website work fine too (with the first example the cube is behind you).

The AR's one don't work but the /quest isn't an AR device.

**Comment by kabrio** [comment]
Oh, really? I just tried the first example and well, I guess I should have turned around!
Thank you very much for the information!

**Comment by kabrio** [comment]
Okay, [example 1](https://editor.p5js.org/stalgiag/present/YsmwJUs83) from p5xr website only works in the built in Oculus Browser and not in Firefox Reality!

**Comment by Vargol** [comment]
Looking at your code I suspect it to do with the use of 2d drawing functions like rect and vertex, the stuff I've used is all spheres and boxes.

Not sure if that's a issue with the Quest is  just p5xr in general not support those ? (yet ?).

Over too stalgiag

**Comment by kabrio** [comment]
Thank you, I will do some tests and see why my code is not working correctly!

**Comment by kabrio** [comment]
> Looking at your code I suspect it to do with the use of 2d drawing functions like rect and vertex, the stuff I've used is all spheres and boxes.

It was my usage of P5js standard background() function that messed it up.
Without it it works fine, even with the 2d functions! :)

**Comment by stalgiag** [comment]
Hi all! Sorry for coming around to this so late! Glad to hear that it is working with the Oculus Quest. I am going to close now for organizational purposes.
