### ISSUE TITLE
Release 0.4.0?

### ISSUE THREAD

**Issue by stalgiag** [stalgiag/p5.xr#117]
Thanks to @msub2 adding a bunch of great fixes & additions, we are probably ready for another release. I will have a bit more time next week to dive back into the code and think about needed changes but in the meantime, I would love to get a wishlist for any additions for the next release. I would love to target the end of the month for a release.

I will take a look at #97 and #72 to see how much work they entail.

**Comment by MChrisGM** [comment]
Controller support?

**Comment by stalgiag** [comment]
Yes this will be added with the next release courtesy of @msub2 's #115

**Comment by MChrisGM** [comment]
Nice! When should we expect it?

**Comment by stalgiag** [comment]
Soon. Likely within the next 2 weeks but if you need it sooner, you can follow [steps 1-5 of 'Setting up Dev Environment' in the Contributor Docs](https://github.com/stalgiag/p5.xr/tree/master/contributor-docs#setting-up-a-development-environment) to build locally.
