### ISSUE TITLE
applyMatrix does not accept TypedArrays

### ISSUE THREAD

**Issue by msub2** [stalgiag/p5.xr#120]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement

#### Which area does this problem relate to?

- [x] VR
- [ ] AR(ARCORE)
- [ ] AR(MARKER)

#### Details about the bug: 

- p5.js version: 1.3.0
- Steps to reproduce this:

So, somewhat embarrassingly, I didn't actually go far enough addressing the need for applyMatrix to accept matrices. I forgot that that the matrix data from XRRigidTransform is a *Float32Array* and not a regular Array. Currently, the upstream change in p5 only checks for a regular array, so you still have to spread pose data for it to be read properly 🙃. I'll have to submit another pull request to address this, but I'll leave this issue open as long as it's still an issue.

**Comment by stalgiag** [comment]
Oops! I briefly wondered to myself whether that `isArray` check would work. Oh well!

**Comment by msub2** [comment]
Change was merged! Looks like they're gonna do a 1.3.1 release soon as well to fix some other bugs, so after that we should be set.

**Comment by msub2** [comment]
1.3.1 is out! `applyMatrix(hand.pose)` *finally* works correctly. Should be able to finally update the tracked controllers example
