### ISSUE TITLE
How to run webxr?

### ISSUE THREAD

**Issue by vedhant** [stalgiag/p5.xr#13]
I am trying out the toonShader example. It shows me "VR not found". I tried a lot if things like enabling certain xr flags in chrome. I'm not able to run it? How to make it run?

**Comment by stalgiag** [comment]
What is your hardware and browser?

**Comment by vedhant** [comment]
My browser is chrome 68 on linux. My computer has i5-7th gen processor, 8gb ram and 2bg 940mx gpu.

**Comment by stalgiag** [comment]
Ah I see. Room-scale or desktop VR isn't currently setup in this repo. I have a working example of that elsewhere but migrating that isn't top priority right now. Mobile is the focus for now.

The current examples only work with a mobile device. The browser should be the newest version of chrome available for your platform. If that is under version 70 then you will need to patch in the webxr-version-shim. If this is necessary I can just do it for the codebase. I wasn't sure how much it would be needed so I omitted the version shim in master.

**Comment by vedhant** [comment]
Does my mobile need to have ARCore for it to work?

**Comment by stalgiag** [comment]
No not for that demo

**Comment by stalgiag** [comment]
@vedhant were you able to run a test? I also added a link to the readme to a test that doesn't require building etc. If you are able to run a test please close this issue for organizational purposes.
