### ISSUE TITLE
Display VR scene under Enter VR button

### ISSUE THREAD

**Issue by smrghsh** [stalgiag/p5.xr#169]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Which area does this problem relate to?

- [x] VR
- [ ] AR(ARCORE)
- [ ] AR(MARKER)

#### New feature details:
Aims to start the sketch in a browser canvas before Enter VR button is clicked and display the Enter VR button over the sketch, so a user can see the scene before entering VR

The idea behind this feature request is to provide users with a preview of the VR experience that they are about to enter. This provides several advantages. This allows a user to see the initial scene, potentially giving a 'hook' or encouragement to entry, like a thumbnail.  Since VR can be very intense and consuming, this also can provide a 'heads up' to the user before they enter a 3D space. For a developer, this allows for a quicker view of the starting environment, potentially speeding up iteration cycles of debugging.

![beforeafter](https://user-images.githubusercontent.com/22751315/179292673-63ed9c21-05af-448d-8a64-17f46f698206.png)

Currently, I believe p5xr does this in order to provide a button that launches the XR experience.
![current](https://user-images.githubusercontent.com/22751315/179165850-8cf8d7b9-fcfc-433f-be3c-2b2d1afb517e.png)

This feature request draws inspiration from the way [three.js projects often provide VR](https://github.com/mrdoob/three.js/blob/master/examples/jsm/webxr/VRButton.js). However, it does not support inline XR or AR; it only supports `immersive-vr`. I have noted that it doesn't support an exit VR button.
![threejs approach](https://user-images.githubusercontent.com/22751315/179166072-0982e2b6-8fb3-4305-9727-c48f39cd6ad9.png)

It also does not support inline xr. Originally, in order to address this, I was trying to load inline XR because it functions as the 2D preview. However, this doesn't work on headset, as headset browsers inform p5xr that they are immersive, and I get errors with the refSpace. Therefore, I propose something like the following. The approach is to render the scene without XR, perform a session check and label button appropriately, and then have the button start the sketch over.
![proposal](https://user-images.githubusercontent.com/22751315/179166235-5d3a007b-0d4d-426a-a1cf-b24338f714b8.png)

In this way, logic that handles whether the experience is VR or AR is kept out of p5vr.

The diagrams can be small without zooming in to the images, so I've included a figma link for easier viewing: 
[Figma Link](https://www.figma.com/file/MO8ffPGo90uwwua4qqyT4W/three.js-vs-p5xr-vs-new-p5xr-XR-launcher?node-id=0%3A1)

@stalgiag

**Comment by smrghsh** [comment]
@stalgiag

**Comment by stalgiag** [comment]
Hi @smrghsh more detail would be helpful here. You could consider adding small drawings or notes about implementation. Also further explanation on why this is important, existing precedents, etc. A macro feature issue is a prime place to keep detailed notes and plans.

**Comment by smrghsh** [comment]
@stalgiag, I've updated with more detail and a plan.

**Comment by smrghsh** [comment]
I was able to load an inline session and then launch immersive with the [immersive web inline example](https://immersive-web.github.io/webxr-samples/inline-session.html) Currently studying that functionality, and will try to emulate that, because it accomplishes this goal

**Comment by stalgiag** [comment]
> @stalgiag, I've updated with more detail and a plan.

looks great!

**Comment by stalgiag** [comment]
closed with #171
