### ISSUE TITLE
Code in _userDraw is run twice per frame

### ISSUE THREAD

**Issue by stalgiag** [stalgiag/p5.xr#17]
Currently the code that is in `_userDraw` is run twice, once per eye. This is very much not good. A workaround will be difficult but this is high priority. A lot of the p5 functions are linked directly to rendering so they have to happen once per eye. The problem is that other aspects of the user's code that change in the draw loop will also change twice.

This might be a central problem with VR and p5. There are a few design options that will introduce unwelcome complexity. The question is whether to add the complexity on the part of the users with something like `xrDraw()` or to implement a solution that can rerender the framebuffer from a different view matrix on the second eye.

Any ideas on this matter are definitely welcome.

**Comment by vedhant** [comment]
This issue needs high priority. The current way of rendering for both eyes is not acceptable as both the eyes are considered separate frames (since ```_userDraw()``` is called separately for both) rather than being considered as a single frame. The right eye is always one frame ahead of left eye. Obviously, if the scene changes quite noticeably in consecutive frames then the left eye and right eye images will have huge differences.

My opinion is that the design changes should be on the library side rather than user side. I think the goal of this library is to convert standard p5 sketches to xr sketches with minimalist changes in the code. It will most probably become quite complicated but it will be worth the user experience.

Once we come to a decision on what to do, I would like to start immediately on this issue.
(should this issue be given an "issue" and "high priority" label ?)

**Comment by stalgiag** [comment]
Okay as stated other than the unstable polyfill this is the most critical problem.

I agree that a solution that doesn't require workarounds on the users part would be ideal, that seems impossible for the time being. There could definitely be something that I am overlooking but the only solution that I can think of that will accomplish this nicely is if:

All p5.RendererGL rendering can be rerouted to a frame buffer. Then the eye drawing can just modify the view matrices appropriately for the frame buffer after binding. It would simplify many things and greatly improve performance. Everything happening twice is terrible for performance for obvious reasons. The geometry cache helps some but doing everything twice is still terrible. So this (the frame buffer solution) should be the long term goal. But I think, and I could be wrong, that this is impossible to do without some changes to the base p5 library. Essentially there would need to be the option to render to a frame buffer instead, and the ability to access that frame buffer. It might be possible to add this functionality over there but that will require discussion.

In the meantime, temporary fixes that are much worse that I have thought of are:

1. requiring every global variable to be held inside of a `vrGlobals` object. Then that object can be reset between eye drawing to prevent doubling of modifications.

2. some p5.Graphics related solution? Didn't pursue this very far because I think it would still require the changes from 1 in order to work correctly.

3. Something that takes the whole p5 sketch file and recreates it in instance mode. Then each instance is run per eye.  This would require very obtuse coding and would be a terrible long term solution.

Those are the only fixes that come to mind. I am very open to others, be they temporary or long-term. I added a version of 1 with #23. This temporary solution can be further improved by figuring out a way to mask the creation of the vrGlobals object. Perhaps there is a way to get all of the globals that are added by the sketch and bind some reference to them so that the user can:
```
var x = 0;

function draw() {
  var x++;
}

```
and p5vr can:
```
if(renderingSecondEye) {
  all properties in vrGlobal // this is just x
  property = state previous to rendering first eye
```
 I am not entirely sure if that is possible. This would most likely require some obtuse code. But this is essentially how it is working in master right now, but without the ability to mask the object creation from the user.

**Comment by stalgiag** [comment]
I took a few moments to browse around for better solutions and I started looking at some features of WebGL2. I've never worked with WebGL2 so I am not really sure how this will work but it seems possible that we can [copy the data in the bound frame buffer](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/copyBufferSubData) after the first pass through userDraw and then modify the view matrices and draw the same data back to the framebuffer. Again, I just glanced at this stuff and I don't know fully understand it but seems like an interesting route.

**Comment by vedhant** [comment]
This is interesting! However, p5 entirely uses webgl1. Will we be able to use webgl2 features?

**Comment by stalgiag** [comment]
Right, but [we can change one line](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L170) in the build that we are testing off of and if that offers an easy solution to a hard problem then I think it would be possible to argue for creating the option to start the context with webgl2 in p5.

There is [precedent for this request in the p5 library](https://github.com/processing/p5.js/issues/2536) and it would be a very simple change to make over there. Again, I don't know whether this works as a solution but certainly worth investigating.

**Comment by stalgiag** [comment]
Okay just a note to track that I wasn't thinking clearly. All options are quite difficult because of the immediate drawing of the base p5 RendererGL.

Current options seem to be:
- Figure out a way to track modelViewMatrices in a separate array then use this info in combination with the `gHash` to 'recreate' the rendering relevant calls from the user on the second eye.
- [OVR_multiView2](https://www.khronos.org/registry/webgl/extensions/OVR_multiview2/): most appealing because of reduction in draw calls and cleanliness but seems like a nightmare to implement. Requires completely modifying all shaders and changing all code for drawing.
- current solution, `{vrGlobals}`, requiring that all global variables are placed in this object which gets reset between eyes. Not awesome.
- above but somehow manually doing that for the user (ie: if somehow possible, detecting all variables added to global by the user's sketch file and manually putting references to them in our own internal `{vrGlobals}`, not fully thought out.

**Comment by stalgiag** [comment]
I just realized that Processing for Android uses `calculate()` for [any calculations that need to occur once every frame.](https://android.processing.org/reference/vr/calculate.html) Since there is precedent, I believe this is the preferable option.

I will implement this soon.
