### ISSUE TITLE
Proposal to Include p5.xr in the New p5 Website Libraries List

### ISSUE THREAD

**Issue by TiborUdvari** [stalgiag/p5.xr#211]
There has been a request to list libraries for the new p5 website https://github.com/processing/p5.js-libraries
I think p5.xr should be included.
Thoughts? @stalgiag 

I can submit the PR myself if you wish, but I thought it should be your decision
The deadline is April 8, 2024 ( two weeks from now ).

**Comment by stalgiag** [comment]
Thanks for bringing this up! No need to worry. I am working on the website project that the examples repo will later be merged into and it already includes p5.xr.
