### ISSUE TITLE
How to Release New Versions

### ISSUE THREAD

**Issue by TiborUdvari** [stalgiag/p5.xr#212]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Feature enhancement details:

I didn't find any info in `contributor-docs` about how to go about making a new release. The last one has been in August 2022 https://github.com/stalgiag/p5.xr/releases/tag/v0.4.65

**Comment by stalgiag** [comment]
Ah I have been doing this manually. I can make a new release this weekend. It might be worth examining how to do this more automatically

**Comment by stalgiag** [comment]
I just released a new version. We can talk about options for making this workflow better in the future.
