### ISSUE TITLE
Hand Tracking Feature Discussion

### ISSUE THREAD

**Issue by TiborUdvari** [stalgiag/p5.xr#216]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Which area does this problem relate to?

- [x] VR
- [x] AR(ARCORE)
- [x] AR(MARKER)

#### New feature details:

I'm looking into implementing hand tracking. According to the [specification](https://www.w3.org/TR/webxr-hand-input-1/), WebXR provides the following `skeleton joints` of each hand.

![hand](https://www.w3.org/TR/webxr-hand-input-1/images/hand-layout.svg)

Here is a handy example implementation: [demo](https://immersive-web.github.io/webxr-samples/immersive-hands.html) [source](https://github.com/immersive-web/webxr-samples/blob/main/immersive-hands.html)

## Proposed v1 p5.xr Behaviour

It should mimic the p5 [touches](https://p5js.org/reference/#/p5/touches) API, to keeps a global updated list. The difference here is that we have orientation information as well, which might be useful.

Most interaction would focus on the finger tips, which should be easily accessible, and indexed according to a [Five Finger System](https://en.wikipedia.org/wiki/Finger_numbering) as in keyboard instruments, to increase access.

![hand](https://evangelisticpiano.com/files/hands.gif)

Hand tracking would be passed in as an `optionalFeatures` and nothing would happen if it is not active.

I would start with implementing an API like this

```js
leftHand // array containing left hand skeletal joint positions
rightHand // array containing left hand skeletal joint positions
leftFingers // array containing left finger tip positions indexed my Five Finger System
rightFingers // array containing left finger tip positions indexed my Five Finger System
leftIndexFinger // position of left index finger
rightIndexFinger // position of right index finger
```

**Comment by TiborUdvari** [comment]
A point of discussion would probably also be  how to return these values efficiently.

In the `p5.js` source code they commonly use this syntax to account for global and instance mode.
```js
this._setProperty('touches', touches);
```

This works for settings primitive values or touch instances because they either set primitives or touches are just a few objects per frame.

I was considering starting with `PVector` to start but I think it would add a lot of work for the garbage collector down the road, I'm going to return a js object containing the data with x, y, z coordinates, similar to how `touches` work instead as a starting point. This way users need to construct a PVector, but they are aware of the construction at least.

**Comment by TiborUdvari** [comment]
Actually, I think some beginner-friendly defaults would be better.
This is a classic first sketch that people like

```js
function draw(){
  ellipse(mouseX, mouseY, 10, 10);
}
```

Having the left hand, right hand etc. in arrays would require to explain iteration, loops, indexes etc. before people can get up and running.

A better way would be having a smart default called `finger` that is the right hand index finger for example to start out quickly and be able to have the same aha experience with p5.xr.

With this in mind here is an updated proposition for the hand-tracking API.

```js
mainHandMode (LEFT, RIGHT)
mainFingerMode(THUMB, INDEX, MIDDLE, RING, LITTLE)

finger - finger tip joint
fingerMain
fingerAlt
fingerLeft
fingerRight

fingers - 10 fingers starting with the main hand fingers
fingersMain
fingersAlt
fingersLeft
fingersRight

hand - list of skeletal joints starting with main hand joints
handMain
handAlt
handLeft
handRight

handIsTracking(MAIN)
handIsTracking(ALT)
handIsTracking(LEFT)
handIsTracking(RIGHT)
```

Some notes
* API always starts with `finger`, `hand` etc to mirror Processing like syntax i.e. `mouseX`.
* There is a `mode` introduced to account for left handed and right handed people. It's hard coming up with good easily type-able variable names for dominant, secondary hand etc.
* `finger` variables actually refer to finger tips, and `hand` contains skeletal joints. The more precise nomenclature is replaced with (hopefully) easy to remember defaults

**Comment by stalgiag** [comment]
Great! I agree with the final API here. There is still some trickiness in naming that we may want to iterate on. Some people may get tripped up on `finger` as the prefix for a single joint when a finger is actually a collection of joints. That said I think it would become unwieldy if these were named "fingerTipMain" so I agree with your final decisions here as long as we keep the door open to further naming iterations.
