### ISSUE TITLE
p5xr does not work with p5 instance mode

### ISSUE THREAD

**Issue by vedhant** [stalgiag/p5.xr#25]
Currently, p5xr only supports p5 global mode.
Also, I am unsure how to use p5 node package instead of manually including p5.js file in assets.

**Comment by stalgiag** [comment]
I don't know if we need to support instance mode.

You can reference the library in 'node_modules'.

**Comment by vedhant** [comment]
p5xr doesn't need to support instance mode. So I'm closing this issue.
