### ISSUE TITLE
Inheriting p5xr from p5

### ISSUE THREAD

**Issue by vedhant** [stalgiag/p5.xr#27]
I think inheriting p5xr from p5 will make it easier to work with p5xr. Adding features should become easier.
I was doing quite a bit of refactoring. I started out trying to do something like this : 
```javascript
p5.prototype.createVRCanvas = function() {
  this.xr = new p5vr(this);
```
```javascript
export default class p5xr {
  constructor(p5_instance) {
    this.p5_instance = p5_instance;
```
There is no inheritance here but I wanted to see how it affects the codebase. It didn't make much difference and had similar issues as the current one.
Then after some thinking, I am more convinced that actual inheritance is a better solution : 
```javascript
import p5 from 'p5';
export default class p5xr extends p5 {

}
```
I used the p5 npm package. So, I came into a problem. p5vr , p5ar extends p5xr which in turn extends p5. Now, instead of p5 objects being initialised p5vr or p5ar must be initialized. I cannot stop the p5 initialisation (init.js in p5 code) as that code from npm is not modifiable. Also, we need to know beforehand whether the sketch will be ar/vr to initialise p5ar/p5vr. Currently this is done in preload. 
The only hurdle is the initialisation part. If we could modify init.js, then we can appropriately initiliase p5ar/p5vr.

**Comment by stalgiag** [comment]
I am a little wary of this approach. How does this change flexibility in terms of library distribution? I also do not think it is wise to modify init.js.

Are there any major issues with requiring that p5 run in global mode? Right now the chain is such that p5.xr objects will not initialized unless the p5 global object exists. I find this to be fairly reasonable but maybe I am missing something?
