### ISSUE TITLE
Problems with Headless Chrome Unit Testing

### ISSUE THREAD

**Issue by vedhant** [stalgiag/p5.xr#36]
```javascript
suite('app', function() {
    let myp5;

    setup(function() {
        console.log(' setup! ');
        // PROBLEM HERE
        myp5 = new p5(); 
        // window.setup = function() {};
        // window.draw = function() {};
        // window.vrGlobals = {};
    });

    teardown(function() {
        myp5.remove();
        // window.setup = undefined;
        // window.draw = undefined;
        // window.vrGlobals = undefined;
        console.log(' teardown! ');
    });

    suite('createVRCanvas()', function() {
        test('p5vr is initialised', function() {
            // createVRCanvas();
            // assert.instanceOf(p5xr.instance, p5vr);
            // p5xr.instance.remove();
        });
    });
    
    suite('setVRBackgroundColor()', function() {
        test('curClearColor is set', function() {
            // createVRCanvas();
            // setVRBackgroundColor();
        });
    });
});
```

Here, clearly there are 2 empty tests with a ```setup()``` which only initialises p5 globally and a ```teardown()``` which removes the global p5 object.

When I run the test, the 1st test passes while the 2nd fails.
error message:
"before each" hook for "curClearColor is set"
Cannot read property 'call' of undefined

I tried digging in a lot. The problem lies in ```myp5 = new p5();``` in setup. Even if I create p5 object by instance mode, i get not such error. It is happening only when it is created globally. Every other thing i do in setup does not give the error. Also, there is a point to note that using ```myp5 = new p5();``` actually creates global p5 object properly and is as expected in the 1st test(#35 shows it). However, the error comes in the second test.

@stalgiag Can you have a look at this? #35 cannot be completed without solving this.

**Comment by stalgiag** [comment]
Try stubbing setup and draw for the p5 object on construction ie = 
```
  setup(function() {
    myp5 = new p5(function(p) {
      p.setup = function() {};
      p.draw = function() {};
    });
  });
```

**Comment by stalgiag** [comment]
I changed the name of this issue to be more vague. Going forward when new issues pop up around the initial setup of unit testing (ie #35) we should use this single issue to report new hurdles in your movement towards that goal.

**Comment by vedhant** [comment]
It is quite strange but when I changed the test style of mocha from tdd to bdd, it works!
```javascript
// mocha.setup('tdd');
```
```javascript
import p5vr from "../../src/p5xr/p5vr/p5vr";

describe('app', function() {
    let myp5;

    before(function() {
        myp5 = new p5();
        window.setup = function() {};
        window.draw = function() {};
        window.vrGlobals = {};
    });

    after(function() {
        myp5.remove();
        window.setup = undefined;
        window.draw = undefined;
        window.vrGlobals = undefined;
    });

    describe('createVRCanvas()', function() {
        it('p5vr is initialised', function() {
            createVRCanvas();
            assert.instanceOf(p5xr.instance, p5vr);
            p5xr.instance.remove();
        });
    });
    
    describe('setVRBackgroundColor()', function() {
        it('curClearColor is set', function() {
            createVRCanvas();
            setVRBackgroundColor();
        });
    });
});
```

Now, I don't get the weird error instead I get a new error only in the 2nd test :
TypeError: navigator.xr.supportsSessionMode is not a function

This is WebXR specific error and nothing to do with mocha. I think there is something weird going around with the tdd style of mocha. If we are moving to the bdd style, then I think it's time we start stubbing the webxr part.

**Comment by vedhant** [comment]
I have found out the exact reason behind these errors.
So, lets say the browser doesn't have webxr api. When I first create p5xr object (as in my 1st test), webxr is polyfilled and `navigator.xr` becomes available.  At the end of the 1st test, I destroy the p5xr object and in the 2nd test I again create p5xr object. However, now as `navigator.xr` already exists, the property `p5xr.injectedPolyfill` becomes false. That is why I was always getting an error in the 2nd test. It explains the error "TypeError: navigator.xr.supportsSessionMode is not a function" (as this function belongs to the non-polyfill). 

When I did a quick fix to this by destroying `navigator.xr`, the error in bdd version disappeared and surprisingly, the weird error in tdd version (Cannot read property 'call' of undefined) also disappeared!

My fix : 
```javascript
this.remove = function() {
  if(self.injectedPolyfill) {
    delete navigator.xr;
  }
  self.xrButton.remove();
  window.p5xr.instance = null;
};
```

This fix produces several warnings while testing :
WARN: 'XR already defined on global.'
WARN: 'XRDevice already defined on global.'
WARN: 'XRSession already defined on global.'
WARN: 'XRFrame already defined on global.'
.
.
.

So, there are two things that needs to be decided : 

- Is the current fix sufficient or requires a better way to destroy the polyfill parts?
- Choose between tdd and bdd. I feel the tdd version doesn't log out errors properly, as the error it was producing was not debugable. Both the versions gave different error logs for the same problem.

#35 can be merged once these two points are decided.

**Comment by vedhant** [comment]
To just sum up things : 

- tdd and bdd of mocha are the same (i did not fairly compare them earlier. I changed the code quite a bit every time I switched between them for testing). Finally, I tested them side by side by trying all possible problematic situations I faced so far and they had same response except in one situation. The tdd version gave error when there is no `window.setup()` and `window.draw()` when `myp5 = new p5()` is run. But, the bdd didn't give such error (it ignored it).

- if webxr is been polyfilled, then the polyfill stuff must be destroyed when p5xr instance is destroyed.

**Comment by stalgiag** [comment]
Yes you can destroy the polyfill for the time being. This has a bunch of annoying side effects and is very likely to cause problems at some point but as has been stated earlier once the polyfill has parity with the browser API again the dual path approach will be removed and the injectedPolyfill boolean will no longer be necessary. For now this seems good just to make sure we can get the unit tests in a workable state. Later when the dual paths are unified, we can remove the deletion of navigator.xr in `p5xr.remove`.

**Comment by vedhant** [comment]
Closing with #35
