### ISSUE TITLE
generateRay() - Raycasting

### ISSUE THREAD

**Issue by vedhant** [stalgiag/p5.xr#45]
```
generateRay(Number x1, Number y1, Number z1, Number x2, Number y2, Number z2) - returns rayObject

rayObject : 
{
  origin: p5.Vector,
  direction: p5.Vector
}
```

**Description**
The generateRay() function will create a ray under the transforms present at the time of this function call. The origin of the ray will be at (x1, y1, z1) and it will be directed towards (x2, y2, z2). The length of the line (x1, y1, z1) (x2, y2, z2) does not matter as the 2nd point only determines the direction. It returns a ray object which can be passed to intersectsSphere(), intersectsBox() and intersectsPlane().

This function allows a ray to be created with respect to a transform and can be used everywhere in the code where the transforms could vary.

**Example**
```javascript
let vrGlobals = {
  counter: 0
};

let randomx = [], randomy = [];

function preload() {
  createVRCanvas();
}

function setup() {
  setVRBackgroundColor(200, 0, 150);
  for (let i = 0; i < 5; ++i) {
    randomx[i] = random(-500, 500);
    randomy[i] = random(-500, 500);
  }
}

function draw() {
  setViewerPosition(0, 0, 400);
  push();
  translate(randomx[0], randomy[0]);
  fill('green');
  sphere(30);
  rotateZ(millis() / 1000);
  line(0, 0, 0, 1000, 1000, 0);
  let ray = generateRay(0, 0, 0, 1000, 1000, 0);
  pop();
  for (let i = 1; i < 5; ++i) {
    push();
    translate(randomx[i], randomy[i]);
    fill('red');
    if (intersectsSphere(70, ray)) {
      fill('blue');
    }
    sphere(70);
    pop();
  }
}

```

**High-level implementation overview**
1. Ray direction is calculated by subtracting (x2, y2, z2) from (x1, y1, z1) and normalised.
2. Ray is transformed under current uMVMatrix.
3. The rayObject is returned.

**Comment by stalgiag** [comment]
closed via #48
