### ISSUE TITLE
Implement hardware support report system

### ISSUE THREAD

**Issue by stalgiag** [stalgiag/p5.xr#56]
Need to make a way for people to report operation on various hardware. Would like to have some support grid.

**Comment by kabrio** [comment]
Just trying to make this run on my Oculus Quest 1 and it doesn't. (Tried example 1)

**Comment by stalgiag** [comment]
Hm -- were you using the Oculus Quest browser? How does it fail exactly?

I don't have any oculus devices, unfortunately.

**Comment by kabrio** [comment]
> Hm -- were you using the Oculus Quest browser? How does it fail exactly?

No, I used Firefox Reality. Works well in Oculus Quest browser!
