### ISSUE TITLE
Raycasting

### ISSUE THREAD

**Issue by stalgiag** [stalgiag/p5.xr#6]
It would be great to have a function that detects whether a ray cast from the camera origin forward in z-space (`p5.instance._renderer.uMVMatrix.mat4[10]`) intersects with or comes within a certain distance of a vec3. This may seem slightly out of scope but it is the only way I can think of to offer interactivity. This would stand in for the kind of interaction we can get with mouseX and mouseY in the 2D renderer.

This may take quite a bit of work.

**Comment by vedhant** [comment]
@stalgiag This will be a starting point to interacting towards virtual 3D objects. Any time we want to select an abject, we should raycast and find if the ray interects the object.
I am willing to implement this as my GSoC project. [XRRay](https://immersive-web.github.io/webxr/#xrray) will be used to create a ray and over the summer I will learn the intersection algorithms and implement it.

**Comment by vedhant** [comment]
The following is the order in which I will be implementing raycasting feature :
1. #43 `intersectsSphere()` - only mouse intersection (without ray argument)
2. #45 `generateRay()`
3. #43 `intersectsSphere()` - finish by supporting ray argument
4. #44 `intersectsBox()`
5. #46 `intersectsPlane()`

**Comment by stalgiag** [comment]
closed via #48, #49, and #50
