### ISSUE TITLE
Test with WebXR viewer for iOS

### ISSUE THREAD

**Issue by stalgiag** [stalgiag/p5.xr#94]
Need [to test with this.](https://apps.apple.com/us/app/webxr-viewer/id1295998056) It doesn't appear to be updated but curious what kind of support we can get as we move forward with adding AR features

**Comment by stalgiag** [comment]
Does not work currently but neither do the official WebXR examples. Seems that there is development of a [different polyfill underway](https://github.com/mozilla-mobile/webxr-polyfill-for-ios-viewer)

**Comment by stalgiag** [comment]
Update - AR works but VR does not work with latest polyfill version. I have contacted the immersive web polyfill developers to figure out the problem.

**Comment by ionif** [comment]
Any update on this?

**Comment by stalgiag** [comment]
Not currently. I was planning to do a more official release once this stabilized but development on the polyfill seems to be at a standstill yet again. Last time that I tried much of the AR functionality was working with Mozilla WebXR viewer but VR is still broken.

**Comment by ionif** [comment]
Okay that sucks but thank you for telling me, is there any main channel to keep track of the webxr development? haven't seen a slack or irc

**Comment by stalgiag** [comment]
The WebXR Viewer listed above has gone out of development with the round of Mozilla layoffs that happened last year. I am closing this issue since it no longer makes sense to develop with that app in mind. Instead, it seems like it will just be a matter of waiting for apple to add webxr support to iOS.
