### ISSUE TITLE
WEBGL mode/usual canvas, when webvr not available?

### ISSUE THREAD

**Issue by zepadovani** [stalgiag/p5.xr#97]
Is it possible to make some sort of conditional that returns an usual 3D canvas (with mouse to control the view) when the VR is not available? (just like a VR switch in youtube does, for instance)

**Comment by stalgiag** [comment]
Hi @zepadovani yes I can add this next time I work on this library. Right now I am waiting to hear back about some issues with the latest version of the webxr-polyfill before continuing work.

Alternatively, If you have an interest in contributing [this example](https://github.com/immersive-web/webxr-samples/blob/master/inline-session.html) is a good starting point.

**Comment by stalgiag** [comment]
After a long time, I finally worked on this today. Most of the functionality is together just need to:
- update projection matrix for inline view,
- fix an out of sync error (may be unrelated)
- and cleanup the code

Will hopefully merge and release by end of March. Sorry it took so long but your request will serve others in the future 🤷 😅
